### ISSUE TITLE
Cisco ASA syntax highlighter for Notepad++

### ISSUE THREAD

**Issue by jimbobmcgee** [linickx/test#4]
The `userDefineLang_ASA.xml` file referenced in [this post](http://www.linickx.com/cisco-asa-syntax-highlighting-with-notepad) is missing, presumably since you migrated your website.

Your [/a](https://github.com/linickx/a) repository seemed the most-likely bet, but I could not see it there.  Thankfully, [archive.org](https://web.archive.org/web/20120527012627/http://www.linickx.com/files/2009/03/userdefinelang_asa.xml) still has a copy, which I have attached for posterity.

[userdefinelang_asa.xml](https://github.com/linickx/test/files/68774/userdefinelang_asa.xml.txt)

**Comment by linickx** [comment]
Hi. Thanks for the heads-up the link in the post is now fixed. Thanks again!
